Repository thepeanutgalleryandco/create-and-mint-nft-collection, pull requests merged in 2022-01, with the labels that each got.

#12 The dash thingy got fixed right ?
  README.md
Labels: documentation, enhancement, good first issue

#13 Fix blank file name skip bug
  src/main.js
Labels: bug

#14 Simple-Get And Canvas Patch
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: documentation, dependencies, security
